sudo: false

os:
  - linux
  - osx

language: c

addons:
  apt:
    packages:
      - ruby
      - shunit2
      - zsh

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install shunit2; fi

before_script:
  - rm -rf $HOME/.rvm $HOME/.rvmrc
  - __rvm_unload
  - export SHUNIT2="$(command -v shunit2 2>/dev/null)"

script: make test
